name: VSCode Extension Version Check

on:
  push:
  schedule:
    # Run weekly on Monday
    # - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  check-extensions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Check for extension updates
        run: python extension_checker.py
        env:
          GITHUB_TOKEN: ${{ secrets.NAMESPACE_CLEANER_TOKEN }}
